- hosts: webservers
  become: true
  tasks:
    - name: Copy env
      ansible.builtin.template:
        src: .env.j2
        dest: '{{ env_file_path }}'
        mode: '0644'

    - name: Start Redmine
      community.docker.docker_container:
        name: redmine
        image: 'redmine:5.1.3'
        restart_policy: always
        state: started
        env_file: '{{ env_file_path }}'
        ports: '80:3000'
