- hosts: all
  become: true
  roles:
    - geerlingguy.pip

  tasks:
    - name: Install Docker package via apt
      ansible.builtin.apt:
        name: python3-docker
        state: present
        update_cache: yes
      tags:
        - prepare-servers

    - name: Copy env
      ansible.builtin.template:
        src: .env.j2
        dest: '{{ env_file_path }}'
        mode: '0644'
      tags:
        - deploy

    - name: Start Redmine
      community.docker.docker_container:
        name: redmine
        image: 'redmine:5.1.3'
        restart_policy: always
        state: started
        env_file: '{{ env_file_path }}'
        ports: '{{ app_port }}:3000'
      tags:
        - deploy

- hosts: webservers
  become: true
  roles:
    - datadog.datadog
  tasks:
    - name: Copy datadog config
      ansible.builtin.template:
        src: datadog.yaml.j2
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
        owner: root
        group: root
        mode: 0644
      tags:
        - prepare-servers

    - name: Start Datadog agent
      service:
        name: datadog-agent
        state: restarted
        enabled: yes
      tags:
        - prepare-servers
