roles:
  - name: geerlingguy.pip
    src: geerlingguy.pip
    version: 3.0.0
  - name: geerlingguy.docker
    src: geerlingguy.docker
    version: 7.4.1
  - name: datadog.datadog
    src: datadog.datadog
    version: 4.28.0
